[package]
name = "parachain-template-node"
version = "0.1.0"
authors = ["Anonymous"]
description = "A new Cumulus FRAME-based Substrate Node, ready for hacking together a parachain."
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/cumulus/"
edition = "2018"
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }

[[bin]]
name = "parachain-collator"
path = "src/main.rs"

[features]
runtime-benchmarks = ["parachain-template-runtime/runtime-benchmarks"]

[dependencies]
derive_more = "0.99.2"
log = "0.4.14"
codec = { package = "parity-scale-codec", version = "2.0.0" }
structopt = "0.3.8"
serde = { version = "1.0.119", features = ["derive"] }
hex-literal = "0.3.1"

# RPC related Dependencies
jsonrpc-core = "18.0.0"

# Local Dependencies
parachain-template-runtime = { path = "../runtime" }
nimbus-primitives = { path = "../../nimbus-primitives"}
nimbus-consensus = { path = "../../nimbus-consensus"}

# Substrate Dependencies
frame-benchmarking = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
frame-benchmarking-cli = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }

pallet-transaction-payment-rpc = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }

substrate-frame-rpc-system = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
substrate-prometheus-endpoint = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }

## Substrate Client Dependencies
sc-basic-authorship = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sc-chain-spec = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sc-cli = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sc-client-api = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sc-consensus = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sc-executor = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sc-network = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sc-keystore = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sc-rpc = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sc-rpc-api = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sc-service = { git = "https://github.com/purestake/substrate", features = ["wasmtime"] , branch = "elois-sig-para" }
sc-telemetry = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sc-transaction-pool = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sc-transaction-pool-api = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sc-tracing = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }

## Substrate Primitive Dependencies
sp-api = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sp-block-builder = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sp-blockchain = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
#sp-consensus = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sp-core = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sp-inherents = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sp-keystore = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sp-offchain = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sp-runtime = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sp-session = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sp-timestamp = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sp-transaction-pool = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }

# Cumulus dependencies
cumulus-client-cli = { git = "https://github.com/purestake/cumulus", branch = "elois-sig-para" }
cumulus-client-collator = { git = "https://github.com/purestake/cumulus", branch = "elois-sig-para" }
cumulus-client-consensus-common = { git = "https://github.com/purestake/cumulus", branch = "elois-sig-para" }
cumulus-client-network = { git = "https://github.com/purestake/cumulus", branch = "elois-sig-para" }
cumulus-client-service = { git = "https://github.com/purestake/cumulus", branch = "elois-sig-para" }
cumulus-primitives-core = { git = "https://github.com/purestake/cumulus", branch = "elois-sig-para" }
cumulus-primitives-parachain-inherent = { git = "https://github.com/purestake/cumulus", branch = "elois-sig-para" }

# Polkadot dependencies
polkadot-cli = { git = "https://github.com/purestake/polkadot", branch = "elois-sig-para" }
polkadot-parachain = { git = "https://github.com/purestake/polkadot", branch = "elois-sig-para" }
polkadot-primitives = { git = "https://github.com/purestake/polkadot", branch = "elois-sig-para" }
polkadot-service = { git = "https://github.com/purestake/polkadot", branch = "elois-sig-para" }
polkadot-test-service = { git = "https://github.com/purestake/polkadot", branch = "elois-sig-para" }
